name: Node CI

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]
    
	steps:
	  - name: Checkout
		  uses: actions/checkout@v1
    
    - name: Use Node.js 
      uses: actions/setup-node@v1
      
    - name: npm install, build
      run: |
        npm ci
        npm run build
      env:
        CI: true
    
    - name: npm publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
